import { Product } from '@/types/products';

export const sampleProducts: Product[] = [
  {
    id: 1,
    name: '1 Pair Arm hand Sleeves For Fashion cycling biking',
    price: 134,
    oldPrice: 550,
    image: '/assets/img/flashsale/01.jpg',
    brand: 'Homtex',
    category: 'Bedding Accessories',
    size: 'M',
    color: 'Black',
    rating: 4.2,
    shippedFrom: 'Dhaka',
    warranty: 'Seller Warranty',
    deliveryOption: true,
    promotions: ['Free Delivery']
  },
  {
    id: 2,
    name: 'Wireless Bluetooth Headphones - Premium Sound',
    price: 89,
    oldPrice: 150,
    image: '/assets/img/flashsale/02.jpg',
    brand: 'Mitu Bedding Store',
    category: 'Electric Blankets',
    size: 'One Size',
    color: 'Black',
    rating: 4.8,
    shippedFrom: 'Chittagong',
    warranty: 'Brand Warranty',
    deliveryOption: true,
    promotions: ['Flash Sale', 'Coins']
  },
  {
    id: 3,
    name: 'Running Shoes Lightweight Mesh',
    price: 67,
    oldPrice: 120,
    image: '/assets/img/flashsale/03.jpg',
    brand: 'Sports House',
    category: 'Pillow Protectors',
    size: 'L',
    color: 'Red',
    rating: 4.5,
    shippedFrom: 'Sylhet',
    warranty: 'No Warranty',
    deliveryOption: false,
    promotions: ['Buy More Save More']
  },
  {
    id: 4,
    name: 'Summer Dress Floral Print Casual Wear',
    price: 45,
    oldPrice: 90,
    image: '/assets/img/flashsale/04.jpg',
    brand: 'Clothika',
    category: 'Bed Sheets',
    size: 'S',
    color: 'Multicolor',
    rating: 3.9,
    shippedFrom: 'Dhaka',
    warranty: 'Seller Warranty',
    deliveryOption: true,
    promotions: ['Mall', 'Free Delivery']
  },
  {
    id: 5,
    name: 'Kitchen Cleaning Sponge Set of 6',
    price: 25,
    oldPrice: 40,
    image: '/assets/img/flashsale/05.jpg',
    brand: 'Proclean',
    category: 'Bathroom Counter Storage',
    size: 'INT',
    color: 'Green',
    rating: 4.0,
    shippedFrom: 'Khulna',
    warranty: 'No Warranty',
    deliveryOption: true,
    promotions: ['Best Price Guaranteed']
  },
  {
    id: 6,
    name: 'Cotton T-Shirt Premium Quality',
    price: 35,
    oldPrice: 60,
    image: '/assets/img/flashsale/06.jpg',
    brand: 'Fibro Vision',
    category: 'Pillows & Bolsters',
    size: 'XL',
    color: 'Pink',
    rating: 4.3,
    shippedFrom: 'Dhaka',
    warranty: 'Seller Warranty',
    deliveryOption: true,
    promotions: ['Free Delivery', 'Coins']
  },
  {
    id: 7,
    name: 'Stainless Steel Water Bottle 1L',
    price: 42,
    oldPrice: 70,
    image: '/assets/img/flashsale/01.jpg',
    brand: 'Reuva International',
    category: 'Bathroom Scales',
    size: 'One Size',
    color: 'Silver',
    rating: 4.6,
    shippedFrom: 'Rajshahi',
    warranty: 'Brand Warranty',
    deliveryOption: false,
    promotions: ['Buy More Save More']
  },
  {
    id: 8,
    name: 'LED Desk Lamp Adjustable Brightness',
    price: 78,
    oldPrice: 120,
    image: '/assets/img/flashsale/02.jpg',
    brand: 'Buear',
    category: 'Toilet Roll Holders',
    size: 'One Size',
    color: 'Gold',
    rating: 4.4,
    shippedFrom: 'Chittagong',
    warranty: 'International Seller Warranty',
    deliveryOption: true,
    promotions: ['Flash Sale']
  },
  {
    id: 9,
    name: 'Yoga Mat Non-Slip Exercise Mat',
    price: 55,
    oldPrice: 85,
    image: '/assets/img/flashsale/03.jpg',
    brand: 'Sports House',
    category: 'Bath Mats',
    size: 'INT',
    color: 'Orange',
    rating: 4.1,
    shippedFrom: 'Dhaka',
    warranty: 'Seller Warranty',
    deliveryOption: true,
    promotions: ['Free Delivery']
  },
  {
    id: 10,
    name: 'Ceramic Coffee Mug Set of 4',
    price: 32,
    oldPrice: 55,
    image: '/assets/img/flashsale/04.jpg',
    brand: 'NO BRAND MART',
    category: 'Bathroom Counter Storage',
    size: 'One Size',
    color: 'Off White',
    rating: 3.8,
    shippedFrom: 'Rangpur',
    warranty: 'No Warranty',
    deliveryOption: false,
    promotions: ['Buy More Save More']
  },
  {
    id: 11,
    name: 'Portable Phone Charger Power Bank 10000mAh',
    price: 95,
    oldPrice: 150,
    image: '/assets/img/flashsale/05.jpg',
    brand: 'International Homeware',
    category: 'Electric Blankets',
    size: 'One Size',
    color: 'Black',
    rating: 4.7,
    shippedFrom: 'Overseas',
    warranty: 'Brand Warranty',
    deliveryOption: true,
    promotions: ['Mall', 'Coins']
  },
  {
    id: 12,
    name: 'Canvas Backpack Casual School Bag',
    price: 58,
    oldPrice: 95,
    image: '/assets/img/flashsale/06.jpg',
    brand: 'Smilcrafts',
    category: 'Pillows & Bolsters',
    size: 'L',
    color: 'Maroon',
    rating: 4.2,
    shippedFrom: 'Sylhet',
    warranty: 'Seller Warranty',
    deliveryOption: true,
    promotions: ['Free Delivery']
  },
  {
    id: 13,
    name: 'Sunglasses UV Protection Polarized',
    price: 48,
    oldPrice: 80,
    image: '/assets/img/flashsale/01.jpg',
    brand: 'Feska',
    category: 'Bedding Accessories',
    size: 'One Size',
    color: 'Beige',
    rating: 4.0,
    shippedFrom: 'Dhaka',
    warranty: 'Seller Warranty',
    deliveryOption: false,
    promotions: ['Best Price Guaranteed']
  },
  {
    id: 14,
    name: 'Smart Watch Fitness Tracker',
    price: 125,
    oldPrice: 200,
    image: '/assets/img/flashsale/02.jpg',
    brand: 'LG 360',
    category: 'Bath Towels',
    size: 'One Size',
    color: 'Light Blue',
    rating: 4.5,
    shippedFrom: 'Chittagong',
    warranty: 'Brand Warranty',
    deliveryOption: true,
    promotions: ['Flash Sale', 'Mall']
  },
  {
    id: 15,
    name: 'Kitchen Knife Set Professional Chef 5 Pieces',
    price: 72,
    oldPrice: 110,
    image: '/assets/img/flashsale/03.jpg',
    brand: 'Keton Trading',
    category: 'Toilet Covers',
    size: 'INT',
    color: 'Light Ash',
    rating: 4.3,
    shippedFrom: 'Khulna',
    warranty: 'Seller Warranty',
    deliveryOption: true,
    promotions: ['Free Delivery']
  },
  {
    id: 16,
    name: 'Bath Towel Soft Cotton Extra Large',
    price: 38,
    oldPrice: 65,
    image: '/assets/img/flashsale/03.jpg',
    brand: 'HOMTEX',
    category: 'Bath Towels',
    size: 'XL',
    color: 'Light Green',
    rating: 4.1,
    shippedFrom: 'Dhaka',
    warranty: 'No Warranty',
    deliveryOption: true,
    promotions: ['Buy More Save More']
  },
  {
    id: 17,
    name: 'Gaming Mouse Wireless RGB',
    price: 82,
    oldPrice: 130,
    image: '/assets/img/flashsale/05.jpg',
    brand: 'Buear',
    category: 'Shower Curtains',
    size: 'One Size',
    color: 'Black',
    rating: 4.6,
    shippedFrom: 'Rajshahi',
    warranty: 'Brand Warranty',
    deliveryOption: false,
    promotions: ['Flash Sale', 'Coins']
  },
  {
    id: 18,
    name: 'Winter Jacket Hooded Warm Coat',
    price: 145,
    oldPrice: 220,
    image: '/assets/img/flashsale/06.jpg',
    brand: 'Clothika',
    category: 'Comforters, Quilts & Duvets',
    size: 'XXL',
    color: 'Blush Pink',
    rating: 4.4,
    shippedFrom: 'Overseas',
    warranty: 'International Seller Warranty',
    deliveryOption: true,
    promotions: ['Mall', 'Free Delivery']
  },
  {
    id: 19,
    name: 'Indoor Plant Pot Ceramic with Stand',
    price: 29,
    oldPrice: 50,
    image: '/assets/img/flashsale/02.jpg',
    brand: 'International Homeware',
    category: 'Bathroom Shelving',
    size: 'M',
    color: 'Multicolor',
    rating: 3.9,
    shippedFrom: 'Rangpur',
    warranty: 'No Warranty',
    deliveryOption: true,
    promotions: ['Best Price Guaranteed']
  },
  {
    id: 20,
    name: 'Bluetooth Speaker Portable Waterproof',
    price: 68,
    oldPrice: 105,
    image: '/assets/img/flashsale/01.jpg',
    brand: 'Mitu Bedding Store',
    category: 'Shower Caddies & Hangers',
    size: 'One Size',
    color: 'Red',
    rating: 4.5,
    shippedFrom: 'Dhaka',
    warranty: 'Brand Warranty',
    deliveryOption: true,
    promotions: ['Flash Sale', 'Free Delivery']
  }
]